### ISSUE TITLE
Black screen after successful install and boot screen

### ISSUE THREAD

**Issue by dmMenezes** [HuskyDG/VMOSPro_ROM#13]
Installation succeeds but after boot splash screen it becomes just black! Cannot access anything at all in the VM.

After enabling GMS I repeatedly get failed message in the vm. I will link a screenshot.
![Screenshot_20211108-041738](https://user-images.githubusercontent.com/38250193/140713231-cfc48292-80a1-4a32-a770-dd7d2f4012ad.png)
![Screenshot_20211108-041732](https://user-images.githubusercontent.com/38250193/140713240-11362c0a-2d1b-4007-b029-34d3d271c92a.png)

Translations. 
1) The system interface has stopped working (close symbol) close app
2) RomEx_CN stopped working (close symbol) close app

**Comment by HuskyDG** [comment]
You could try using official ROM to check if this is my ROM problem or original ROM problem

**Comment by ILMOE** [comment]
Same here, black screen after boot up animation, not even the 4 icons that @dmMenezes had in his screenshoot

**Comment by dmMenezes** [comment]
> Same here, black screen after boot up animation, not even the 4 icons that @dmMenezes had in his screenshoot

There is a trick to follow. Will not help though.

I installed older version of vmos. Version 1.0 if u remember correctly.
Then once i get black screen, I stopped VM and went to VM settings and enabled GMS.
And then booted up again.

**Comment by dmMenezes** [comment]
BTW, I found a fix.

You should be on latest version to boot in I think.
The author of this repository has another repository for moded vmos. Just download that and turn off you wifi and do the startup process on mobile data. Once you boot in try using wifi. I could use wifi after few reboots.

It's running just fine now!! 
Hope this helps.
Regards

**Comment by dmMenezes** [comment]
> You could try using official ROM to check if this is caused by my ROM or original ROM itself

Hey! 
I figured it out! It was not problem with your ROM.
Sorry for raising an issue. 
Its problem with the app.

**Comment by ILMOE** [comment]
> BTW, I found a fix.
> 
> You should be on latest version to boot in I think. The author of this repository has another repository for moded vmos. Just download that and turn off you wifi and do the startup process on mobile data. Once you boot in try using wifi. I could use wifi after few reboots.
> 
> It's running just fine now!! Hope this helps. Regards

hey thank you, it worked very well with the modded Vmos app
