### ISSUE TITLE
New ROM Android 7.1.2 Premium 32 bit Blackscreen in all vmos ver

### ISSUE THREAD

**Issue by keramak** [HuskyDG/VMOSPro_ROM#2]
Hello im facing problem while starting vmos using New rom android 7.1.2 premium 32bit, how to fix it 
thank you

**Comment by HuskyDG** [comment]
Hi, there.
I have noticed about your problem and I am working on it...
Thanks for the report!

**Comment by HuskyDG** [comment]
[Problem solved]
I have fixed the black screen problem which is caused by missing neccessary files

**Comment by keramak** [comment]
Thanks dev, now working properly
