### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by A2A410** [HuskyDG/VMOSPro_ROM#3]
Rom installation failed, please check whether the ROM is stored!

**Comment by HuskyDG** [comment]
Try rename zip to `rom.zip` then import
Make sure the path to zip doesn't include space character

**Comment by A2A410** [comment]
I already did that but still do not work.

**Comment by HuskyDG** [comment]
Send me screenshot of zip in your file manager

**Comment by A2A410** [comment]
I thought the problem is, i downloaded it on MEGA.
It was stored on /sdcard/MEGA/Mega Downloads/rom.zip .
I moved it on download folder.
