### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by lucasguedesrj** [HuskyDG/VMOSPro_ROM#9]
Does not back up contacts.
Android 7

**Comment by HuskyDG** [comment]
There are problem with Contacts on Android 7.1.2
You can apply LP Patchs to fix this

**Comment by HuskyDG** [comment]
Contact was added to Android 7.1.2 64bit ROM VMOS PRO v1.4.6

**Comment by 272development** [comment]
HuskyDG - I am using your 7.1.2 pruor to contact fix.  It is a heavy container with a lot of installs.  Can you give me the steps to fix or install contacts?  LP installed.

Thank you
